#!/usr/bin/env bash
# Configures an Nginx server
# Nginx should be listen on port 80
# Serve/returns  a page that would return a Hello World string
#

echo -e "System Update and install Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

# starting nginx service
sudo service nginx start

# allowing nginx on uncomplicated firewall (ufw)
sudo ufw allow 'Nginx HTTP'


# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

echo -e "\nDone.\n"
