#!/usr/bin/env bash
# Displays a list of currently running processes.
#   Requirements:
#+   Must show all processes, for all users, non-TTY users
#+   Display in a user-oriented format
#+   Show process hierarchy

ps -faux
