#!/usr/bin/env bash
# Displays "Holberton School" 10 times using a while loop.
# check if i = 9 during iteration

i=0;

while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi

	((i++))
done
