#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

hr=0

while [ $hr -lt 13 ]
do
  echo "Hour: $hr"
  min=1
  while [ $min -lt 60 ]
  do
    echo "$min"
    (( min++ ))
  done
  (( hr++ ))
done
